## Elasticsearch

# Gather rpm package facts
- name: Gather rpm package facts
  package_facts:
    manager: auto
    
# Install elasticsearch
- name: Install Elasticsearch
  apt:
    name: elasticsearch
    update_cache: yes
  when: "'elasticsearch' not in ansible_facts.packages"
  notify: restart elasticsearch

- name: Configure elasticsearch
  template:
    src: "{{ elasticsearch_config_tpl }}"
    dest: "{{ elasticsearch_config_dest }}"
    mode: "0644"
  notify: restart elasticsearch

# Start elasticsearch
- name: Start Elasticsearch
  service:
    name: elasticsearch
    state: started
    enabled: true

