## Elasticsearch

# Gather rpm package facts
- name: Gather rpm package facts
  package_facts:
    manager: auto
    
# Install elasticsearch
- name: Install Elasticsearch
  apt:
    name: elasticsearch
    update_cache: yes
  when: "'elasticsearch' not in ansible_facts.packages"

# Start elasticsearch
- name: Start Elasticsearch
  service:
    name: elasticsearch
    state: started
    enabled: true

